name: secure_cred
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  smooth_page_indicator: ^1.1.0
  random_avatar: ^0.0.8
  get: 4.6.6
  cached_network_image: 3.3.1
  page: 1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
  assets: 
    - assets/images/
    - assets/samples/
    - assets/images/miscs/
  uses-material-design: true

